### ISSUE TITLE
Not compatible with latest eslint version?

### ISSUE THREAD

**Issue by Andrenie365** [bpmn-io/eslint-plugin-bpmn-io#11]
__Describe the Bug__

When i attempt to upgrade to the latest eslint version, 
it gives following error output:

While resolving: eslint-plugin-bpmn-io@0.12.0
Found: eslint@8.0.1
node_modules/eslint
  dev eslint@"8.0.1" from the root project
  peer eslint@">= 4.12.1" from babel-eslint@10.1.0
  node_modules/babel-eslint
    babel-eslint@"^10.1.0" from eslint-plugin-bpmn-io@0.12.0
    node_modules/eslint-plugin-bpmn-io
      dev eslint-plugin-bpmn-io@"^0.12.0" from the root project
  peer eslint@">=7.0.0" from eslint-plugin-mocha@8.0.0
  node_modules/eslint-plugin-mocha
    eslint-plugin-mocha@"^8.0.0" from eslint-plugin-bpmn-io@0.12.0
    node_modules/eslint-plugin-bpmn-io
      dev eslint-plugin-bpmn-io@"^0.12.0" from the root project
  peer eslint@">=5" from eslint-utils@3.0.0
  node_modules/eslint/node_modules/eslint-utils
    eslint-utils@"^3.0.0" from eslint@8.0.1

Could not resolve dependency:
peer eslint@"^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0" from eslint-plugin-bpmn-io@0.12.0
node_modules/eslint-plugin-bpmn-io
  dev eslint-plugin-bpmn-io@"^0.12.0" from the root project

Conflicting peer dependency: eslint@7.32.0
node_modules/eslint
  peer eslint@"^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 || ^7.0.0" from eslint-plugin-bpmn-io@0.12.0
  node_modules/eslint-plugin-bpmn-io
    dev eslint-plugin-bpmn-io@"^0.12.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

__Steps to Reproduce__

Attempt to upgrade to eslint@latest

__Expected Behavior__

Upgrading previous versions have not given any problems.

__Environment__
VSCode NodeJS

eslint-plugin-bpmn-io : 0.12.0
eslint: 7.32

**Comment by nikku** [comment]
I'll have a look.

**Comment by nikku** [comment]
`eslint@8` is freshly released. While we could mark it as supported certain downstream plug-ins we depend on (`eslint-plugin-react`) do not support it yet. 

I suggest you to keep back the upgrade for the moment and allow plug-in authors to upgrade their plug-ins.

**Comment by nikku** [comment]
Currently blocked by https://github.com/eslint/eslint/issues/15157, so indeed not compatible for the time being.

**Comment by Andrenie365** [comment]
All right. Thank you for the reply 👍 .
