### ISSUE TITLE
Support `eslint@9`

### ISSUE THREAD

**Issue by nikku** [bpmn-io/eslint-plugin-bpmn-io#19]
### Is your feature request related to a problem? Please describe.

The configuration exposed by this library does currently not support `eslint@9`. Trying to use it in a simple project crashes and burns in interesting ways:

```javascript
// eslint.config.js
const recommended = require('eslint-plugin-bpmn-io/configs/recommended');

module.exports = [
  recommended,
  {
    "ignores": [
      "dist"
    ]
  }
];
```

This yields an error, as the configuration exposed is not in `eslint@9` compatible format:

```sh
> eslint .

Oops! Something went wrong! :(

ESLint: 9.7.0

A config object is using the "env" key, which is not supported in flat config system.

Flat config uses "languageOptions.globals" to define global variables for your files.

Please see the following page for information on how to convert your config object into the correct format:
https://eslint.org/docs/latest/use/configure/migration-guide#configuring-language-options

If you're not using "env" directly (it may be coming from a plugin), please see the following:
https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config
```

### Describe the solution you'd like

* [x] The configurations exposed by this library are suitable for inclusion in `eslint@9` setups.
* [x] ESLint@8 is EOL, and hence we want to drop v8 support all together and move directly to v9

### Describe alternatives you've considered

None.

### Additional context

None.

**Comment by barmac** [comment]
After the migration, the JSX became React-centric which breaks non-React-but-JSX projects like camunda-dmn-js:

```
/Users/maciej/workspace/bpmn-io/camunda-dmn-js/lib/camunda-platform/features/simple-date-edit/components/OutputDateEdit.js
  69:7   error  'React' must be in scope when using JSX                  react/react-in-jsx-scope
  69:12  error  Unknown property 'class' found, use 'className' instead  react/no-unknown-property
  71:9   error  'React' must be in scope when using JSX                  react/react-in-jsx-scope
  71:13  error  Unknown property 'class' found, use 'className' instead  react/no-unknown-property
  73:9   error  'React' must be in scope when using JSX                  react/react-in-jsx-scope
  73:13  error  Unknown property 'class' found, use 'className' instead  react/no-unknown-property
  75:9   error  'React' must be in scope when using JSX                  react/react-in-jsx-scope
  76:11  error  'React' must be in scope when using JSX                  react/react-in-jsx-scope
  84:11  error  'React' must be in scope when using JSX                  react/react-in-jsx-scope
  85:22  error  'React' must be in scope when using JSX                  react/react-in-jsx-scope
```

**Comment by barmac** [comment]
The errors come from an inferno-js project.

**Comment by nikku** [comment]
Cf. https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/react-in-jsx-scope.md. 

I propose that we disable this rule, i.e. use the `jsx-runtime` preset in this case.

**Comment by barmac** [comment]
I think it makes sense. And I will add an exception for `class` as the attribute.

**Comment by nikku** [comment]
Alternative: Separate `jsx` and `react` configs.

**Comment by barmac** [comment]
`jsx-runtime` triggers unused variable error for React, but we would like to accept both.

Regarding the yet another config, I'd rather not introduce it right now as it's a new feature. I believe we can have relaxed rules for React and still be successful.
