### ISSUE TITLE
Require Empty Lines Before Comments

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/eslint-plugin-bpmn-io#5]
I'm tired of seeing

```javascript
it('should look awkward', function() {
  // given
  var foo = 'foo';

  // when
  foo = 42;

  // then
  expect(foo).to.equal(42);
});

```

Empty lines before a comment should be required. See https://eslint.org/docs/rules/lines-around-comment.

**Comment by nikku** [comment]
:tada:

**Comment by nikku** [comment]
Can you fix the PR? Looks like you pass an invalid configuration.

**Comment by barmac** [comment]
Closed via https://github.com/bpmn-io/eslint-plugin-bpmn-io/pull/6
