### ISSUE TITLE
Compatibility with ESLint 7.x

### ISSUE THREAD

**Issue by rittmeier** [bpmn-io/eslint-plugin-bpmn-io#9]
__Is your feature request related to a problem? Please describe__
We tried to use eslint-plugin-bpmn-io with the latest version (7.4.0) of eslint. We get the following warning
> npm WARN eslint-plugin-bpmn-io@0.11.0 requires a peer of eslint@^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

__Describe the solution you'd like__

Adjust package.json so that eslint@^7.0.0 is allowed and warning isn`t issued anymore - if eslint-plugin-bpmn-io is compatible.

__Describe alternatives you've considered__

We install eslint@6.x.x :-/

**Comment by pinussilvestrus** [comment]
Thanks for reporting! We are open for contributions which improve the situation 👍

**Comment by nikku** [comment]
Will be fixed via https://github.com/bpmn-io/eslint-plugin-bpmn-io/pull/10.
